# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b08ac38c3766207abfa052ba43b2d52b1f3f978e0bc6e65751dcf445fb375776392b90a41af1278ae0f3a467dc187f0a85656556895493b5764fcf021eecc35f

test:
  secret_key_base: c742ef9dae44486fc1b5b527257f175efa2d9252af051a856c6a23b8fe6250ceada23488349862f8f7816126fb5e727fd4954a84085308b0a5b46500365dcf19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
